#!/bin/sh

VERSION=../VERSION.txt
OUT=log/deployments.log

if [ ! -f $VERSION ]; then
  echo "can't find version file in $VERSION"
  exit 1
fi

echo "SRC REV: "`cat $VERSION 2>&1`

(
  echo "========================================================="
  date
  echo "SRC REV: "`cat $VERSION 2>&1`
) >>$OUT

git pull

(
  echo "DEST REV: "`cat $VERSION 2>&1`
  echo
) >>$OUT

echo "DEST REV: "`cat $VERSION 2>&1`
